# Generated by Django 4.0 on 2021-12-21 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='profile_pics\\i.jpg', upload_to='profile_pics'),
        ),
    ]
