# Generated by Django 4.0 on 2021-12-22 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('photos', '0004_photo_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
