# Generated by Django 4.0 on 2021-12-22 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0006_alter_comment_photo_alter_photo_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='image',
        ),
        migrations.CreateModel(
            name='PhotoImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='posts')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='photos.photo')),
            ],
        ),
    ]
