# Generated by Django 4.0 on 2021-12-22 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0008_photo_image_delete_photoimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='name',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
